### PR TITLE
adding line_match

### PR DESCRIPTION
**Pull request by kay0u**
to be merged if
[Build Status/badge/icon)](http://ci-apps-dev.yunohost.org/jenkins/job/minetest_ynh%20(Kay0u)/)
passed

### CODE REVIEW

**Comment by kay0u** [comment]
I have to change the `30000` in the line match to `$port`

**Comment by kay0u** [comment]
can be merged (I can't on my side)

**Comment by Rafi594** [comment]
conflicting files... I try to fix it

**Comment by Rafi594** [comment]
Fixed by https://github.com/Rafi594/minetest_ynh/commit/fcaab2c4d90ebe5a8822fa37087b40357e40a02c

**Pull request closed without merging**
